Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,6 @@ on:
   push:
     branches:
       - feature
-      - dev
 
 jobs:
   Deploying_to_Development:
@@ -32,22 +31,23 @@ jobs:
           java-version: 17
 
       - name: Publish to Exchange
+        shell: bash
         run: |
           # Extract artifact name from pom.xml
-            echo "Extracting artifact name..."
-            ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
-            echo "Extracted Artifact Name: ${ARTIFACT_NAME}"
-            
-            if [[ -z "${ARTIFACT_NAME}" ]]; then
-              echo "Error: Artifact name could not be determined."
-              exit 1
-            fi
+          echo "Extracting artifact name..."
+          ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
+          echo "Extracted Artifact Name: ${ARTIFACT_NAME}"
+          
+          if [[ -z "${ARTIFACT_NAME}" ]]; then
+            echo "Error: Artifact name could not be determined."
+            exit 1
+          fi
 
-           # Extract GitHub branch name
-            BRANCH_NAME=${GITHUB_REF_NAME}
-            echo "Detected GitHub Branch Name: ${BRANCH_NAME}"
-            APPLICATION_NAME="${ARTIFACT_NAME}-${BRANCH_NAME}"
-            echo "Final Application Name: ${APPLICATION_NAME}"
+          # Extract GitHub branch name
+          BRANCH_NAME=${GITHUB_REF_NAME}
+          echo "Detected GitHub Branch Name: ${BRANCH_NAME}"
+          APPLICATION_NAME="${ARTIFACT_NAME}-${BRANCH_NAME}"
+          echo "Final Application Name: ${APPLICATION_NAME}"
 
           # Publish to Exchange
           mvn deploy --settings .maven/settings.xml -DskipMunitTests \
@@ -56,8 +56,9 @@ jobs:
             -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
 
       - name: Build and Deploy to CloudHub
+        shell: bash
         run: |
-          echo "Deploying to CloudHub with artifact suffix: ${ARTIFACT_SUFFIX}"
+          echo "Deploying to CloudHub with artifact suffix: ${ARTIFACT_NAME}-${GITHUB_REF_NAME}"
           mvn deploy --settings .maven/settings.xml -DskipMunitTests -DmuleDeploy \
             -Dclient.id="${{ secrets.CLIENT_ID }}" \
             -Dclient.secret="${{ secrets.CLIENT_SECRET }}" \
