Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,7 +7,6 @@ on:
   push:
     branches:
       - feature
-      - dev
 
 jobs:
   Deploying_to_Development:
@@ -34,16 +33,21 @@ jobs:
       - name: Publish to Exchange
         run: |
           # Extract artifact name from pom.xml
-          ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
-          if [[ -z "${ARTIFACT_NAME}" ]]; then
-            echo "Error: Artifact name could not be determined."
-            exit 1
-          fi
-          echo "Artifact Name: ${ARTIFACT_NAME}-${{ secrets.ENV }}"
+            echo "Extracting artifact name..."
+            ARTIFACT_NAME=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
+            echo "Extracted Artifact Name: ${ARTIFACT_NAME}"
+            
+            if [[ -z "${ARTIFACT_NAME}" ]]; then
+              echo "Error: Artifact name could not be determined."
+              exit 1
+            fi
+            
+            APPLICATION_NAME="${ARTIFACT_NAME}-dev"
+            echo "Final Application Name: ${APPLICATION_NAME}"
 
           # Publish to Exchange
           mvn deploy --settings .maven/settings.xml -DskipMunitTests \
-            -DapplicationName="${ARTIFACT_NAME}-${{ secrets.ENV }}" \
+            -DapplicationName="${APPLICATION_NAME}" \
             -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
             -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}"
 
